version: '3'
services:
  frontend:
    image: chokshi/frontend:latest
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: chokshi/backend:latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    ports:
      - '3001:3001'
    networks:
      - app_network
    environment:
      - JWT_SECRET=SDNCN23423TN394UFKND
      - MONGO_URL=mongodb+srv://charan03:030904@clusterecoverse.xxoya0d.mongodb.net/ecoverse
      - jwt_token=dhfmharnca394020
      - NODE_OPTIONS=--max-old-space-size=4196

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=g3Fv81iYIm2tnuB+VySG  # Set an initial password for Elasticsearch
      - xpack.security.enabled=false  # Ensure security is enabled
      - ES_JAVA_OPTS=-Xmx2g -Xms2g
    ports:
      - '9200:9200'
    networks:
      - app_network
    volumes:
      - es_data:/usr/share/elasticsearch/data
    mem_limit: 2g    

  # Logstash service
  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.1
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - ELASTIC_USERNAME=elastic  # Elasticsearch username
      - ELASTIC_PASSWORD=g3Fv81iYIm2tnuB+VySG  # Elasticsearch password
    ports:
      - '5044:5044'  # This port will be used by Filebeat to send logs
    networks:
      - app_network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # Logstash pipeline config

  # Kibana service
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICE_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYTpibWJKRWZ2dVN4VzF4VGNCeGlFM1NB
    ports:
      - '5601:5601'  # Kibana's default web UI port
    networks:
      - app_network

  # Filebeat service
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Mount Docker container logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml  # Mount custom Filebeat config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOGSTASH_HOST=logstash:5044  # Configure Filebeat to send logs to Logstash
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  es_data:
    driver: local
