apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mern-app
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: charansrisai/backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3001
        env: 
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: MONGO_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: JWT_SECRET
        - name: jwt_token
          valueFrom:
            secretKeyRef:
              name: mern-backend-secret
              key: jwt_token

